# Lattice Planner Configuration

lattice_planner:
  ros__parameters:
    # Reference path (relative to package)
    reference_path_file: "Spielberg_global"  # Will be resolved to package/config/reference_paths/
    path_resolution: 0.1
    
    # Planning parameters
    lateral_step: 0.5           # Lateral sampling step (m)
    max_lateral_offset: 2.0     # Maximum lateral offset (m)
    planning_horizon: 5.0       # Planning time horizon (s)
    dt: 0.2                     # Time step (s)
    planning_frequency: 10.0    # Planning frequency (Hz)
    
    # Vehicle parameters
    max_velocity: 10.0          # Maximum velocity (m/s)
    wheelbase: 0.33             # Vehicle wheelbase (m)
    max_curvature: 1.0          # Maximum path curvature (1/m)
    
    # Cost weights (for future implementation)
    obstacle_cost_weight: 10.0
    
    # Safety parameters
    safety_margin: 0.3          # Safety margin around obstacles (m)
    collision_radius: 0.5       # Vehicle collision radius (m)
    obstacle_detection_range: 8.0  # Obstacle detection range (m)